services:

    ############################
    #### PROCESSOR
    ############################

    victoire.vacuum_bundle.word_press_processor:
        class: Victoire\DevTools\VacuumBundle\Processor\WordPressProcessor

    ############################
    #### PIPELINE
    ############################

    victoire.vacuum_bundle.io_word_press.pipeline:
        class: Victoire\DevTools\VacuumBundle\Pipeline\WordPress\IOWordPressPipeline
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%"
            - "@victoire.vacuum_bundle.media_formater.utils"

    ############################
    #### UTILS
    ############################

    victoire.vacuum_bundle.media_formater.utils:
        class: Victoire\DevTools\VacuumBundle\Utils\Media\MediaFormater
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%"